version: "3.6"
networks:
  pyspark_network:
services:
  pyspark:
    image: jupyter/pyspark-notebook
    hostname: pyspark
    networks:
      - pyspark_network
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./metrics.properties:/usr/local/spark-3.3.1-bin-hadoop3/conf/metrics.properties
