#! /usr/bin/env bash

chmod -R +x ./bin
chmod -R 777 ./work

MSYS_NO_PATHCONV=1 docker compose stop &&
  docker compose rm -f &&
  docker compose pull &&
  docker compose build &&
  docker compose up --remove-orphans
