receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    verbosity: detailed
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers:
        - otlp
      exporters:
        - loki
        - logging
