{
 "title": "Spark Applications",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "application_name",
    "label": "Application",
    "query": {
     "query": "label_values(metrics_executor_totalDuration_seconds_total,application_name)"
    }
   },
   {
    "name": "executor_id",
    "label": "Executors",
    "query": {
     "query": "label_values(metrics_executor_totalDuration_seconds_total{application_name=~\"$application_name\"},executor_id)"
    }
   },
   { "name": "LOKI", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=~\"$application_name\", level=~\"$level\"}"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Success Rate by Application",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "1 - sum(increase(metrics_executor_failedTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name)\r\n/\r\nsum(increase(metrics_executor_totalTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate by Executor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "1 - sum(increase(metrics_executor_failedTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (executor_id)\r\n/\r\nsum(increase(metrics_executor_totalTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (executor_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(metrics_executor_memoryUsed_bytes{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}) by (application_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Storage Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}) by (application_name)\r\n/\r\nsum(metrics_executor_maxMemory_bytes{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}) by (application_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_MonitoringYarn_driver_BlockManager_memory_memUsed_MB_Value{}/metrics_MonitoringYarn_driver_BlockManager_memory_maxMem_MB_Value{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks on Executor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_totalTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (executor_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Active Tasks on Executor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_activeTasks{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (executor_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Completed Tasks on Executor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_completedTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (executor_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Tasks on Executor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_failedTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (executor_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Executor GC time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(increase(metrics_executor_totalGCTime_seconds_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (executor_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Applications Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  max(metrics_executor_totalDuration_seconds_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"})\r\n  by (application_name)[$__rate_interval:1m]\r\n)"
    }
   ]
  },
  {
   "title": "Total Duration / Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_executor_totalDuration_seconds_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_failedTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name)",
     "legendFormat": "{{application_name}} - Failed"
    },
    {
     "expr": "sum(increase(metrics_executor_totalTasks_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name)",
     "legendFormat": "{{application_name}} - Total"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_activeTasks{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name, executor_id)",
     "legendFormat": "{{application_name}} - {{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}) by (application_name, executor_id)",
     "legendFormat": "{{application_name}} - {{executor_id}} - Consumed"
    },
    {
     "expr": "sum(metrics_executor_maxMemory_bytes{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}) by (application_name, executor_id)",
     "legendFormat": "{{application_name}} - {{executor_id}} - Total"
    }
   ]
  },
  {
   "title": "Executor GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(increase(metrics_executor_totalGCTime_seconds_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name, executor_id)",
     "legendFormat": "{{application_name}} - {{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_totalShuffleRead_bytes_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name, executor_id)",
     "legendFormat": "{{application_name}} - {{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_totalShuffleWrite_bytes_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name, executor_id)",
     "legendFormat": "{{application_name}} - {{executor_id}}"
    }
   ]
  },
  {
   "title": "Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(metrics_executor_totalInputBytes_bytes_total{application_name=~\"$application_name\", executor_id=~\"$executor_id\"}[$__rate_interval])) by (application_name, executor_id)",
     "legendFormat": "{{application_name}} - {{executor_id}}"
    }
   ]
  }
 ]
}